name: "Podman Setup"
description: "Sets up Podman"
inputs:
  runner:
    description: "The runner type (e.g., macos-latest, ubuntu-latest)"
    default: ubuntu-latest
    required: true
runs:
  using: "composite"
  steps:
    - name: Podman constraints
      shell: bash
      run: |
        if [[ ! "${{ inputs.runner }}" =~ ^macos.* && ! "${{ inputs.runner }}" =~ ^ubuntu.* ]]; then
          echo "::error::Podman is only supported on macOS and Ubuntu"
          exit 1
        fi
    - name: Podman setup
      shell: bash
      if: ${{ inputs.runner == 'ubuntu-latest' }}
      run: |
        curl -fsSL "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/Release.key" | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
        sudo apt-get update
        sudo apt-get -y install podman
        systemctl enable --now --user podman podman.socket
        podman info
    - name: Podman setup (macOS)
      shell: bash
      if: ${{ startsWith(inputs.runner, 'macos') }}
      run: |
        PODMAN_VERSION="5.0.0"
        PKG_URL="https://github.com/containers/podman/releases/download/v${PODMAN_VERSION}/podman-installer-macos-universal.pkg"

        echo "Downloading Podman ${PODMAN_VERSION} universal installer..."
        curl -fsSL -o /tmp/podman-installer.pkg "${PKG_URL}"

        echo "Installing Podman..."
        sudo installer -pkg /tmp/podman-installer.pkg -target /

        echo "Adding Podman to PATH..."
        echo "/opt/podman/bin" >> $GITHUB_PATH

        echo "Initializing Podman machine with QEMU..."
        /opt/podman/bin/podman machine init --virt qemu

        echo "Starting Podman machine..."
        /opt/podman/bin/podman machine start

        echo "Podman info:"
        /opt/podman/bin/podman info

    - name: Configure Docker context for Podman (Ubuntu)
      shell: bash
      if: ${{ inputs.runner == 'ubuntu-latest' }}
      run: |
        export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/run/user/$(id -u)}
        docker context create podman --docker "host=unix://${XDG_RUNTIME_DIR}/podman/podman.sock"
        docker context use podman

    - name: Configure Docker context for Podman (macOS)
      shell: bash
      if: ${{ startsWith(inputs.runner, 'macos') }}
      run: |
        PODMAN_SOCK=$(/opt/podman/bin/podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}')
        docker context create podman --docker "host=unix://${PODMAN_SOCK}"
        docker context use podman
