name: "Orbstack Setup"
description: "Sets up Orbstack"
inputs:
  runner:
    description: "The runner type (e.g., macos-latest)"
    default: macos-latest
runs:
  using: "composite"
  steps:
    - name: Orbstack constraints
      shell: bash
      run: |
        if [[ ! "${{ inputs.runner }}" =~ ^macos.* ]]; then
          echo "::error::Orbstack is only supported on macOS"
          exit 1
        fi
    - name: Orbstack setup
      shell: bash
      run: |
        brew install --cask orbstack

        echo "Wait for OrbStack to be ready"
        TIMEOUT_SECS=60
        for i in $(seq 1 ${TIMEOUT_SECS}); do
            if orb version &>/dev/null; then
              echo "OrbStack is ready after ${i}s"
              break
            fi
            echo "Waiting for OrbStack to start... ${i}s"
            sleep 1
        done

        orb version
        orb list

        echo "Wait for Docker socket"
        for i in $(seq 1 60); do
            if [ -e "$HOME/.orbstack/run/docker.sock" ]; then
              echo "OrbStack Docker socket available after ${i}s"
              break
            fi
            sleep 1
        done

        docker context use orbstack
