name: "Colima Setup"
description: "Sets up Colima"
inputs:
  runner:
    description: "The runner type (e.g., macos-latest)"
    default: macos-latest
runs:
  using: "composite"
  steps:
    - name: Colima constraints
      shell: bash
      run: |
        if [[ ! "${{ inputs.runner }}" =~ ^macos.* ]]; then
          echo "::error::Colima is only supported on macOS"
          exit 1
        fi
    - name: Colima setup
      shell: bash
      run: |
        brew install lima-additional-guestagents docker colima
        # Patch lima after https://github.com/abiosoft/colima/issues/970
        LIMACTL_PATH=$(brew --prefix)/bin/limactl
        sudo curl -L -o $LIMACTL_PATH https://github.com/mikekazakov/lima-nohvf/raw/master/limactl && sudo chmod +x $LIMACTL_PATH
        colima start --network-address --arch arm64 --vm-type=qemu --cpu 3 --memory 14 --disk 14 --runtime docker
        colima status
        colima --version
        echo "DOCKER_HOST=unix://${HOME}/.colima/default/docker.sock" >> $GITHUB_ENV
    - name: Print Colima logs
      if: always()
      shell: bash
      run: cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
