name: "Colima Setup"
description: "Sets up Colima"
inputs:
  runner:
    description: "The runner type (e.g., macos-latest)"
    default: macos-latest
  colima-runtime:
    description: "Container runtime to use (docker or containerd)"
    default: docker
runs:
  using: "composite"
  steps:
    - name: Colima constraints
      shell: bash
      run: |
        if [[ ! "${{ inputs.runner }}" =~ ^macos.* ]]; then
          echo "::error::Colima is only supported on macOS"
          exit 1
        fi
    - name: Colima setup
      shell: bash
      run: |
        brew install lima-additional-guestagents docker colima
        colima list
        colima start --cpu 3 --memory 14 --disk 14 --runtime ${{ inputs.colima-runtime }}
        colima status
        colima --version
    - name: nerdctl install (containerd runtime)
      if: ${{ inputs.colima-runtime == 'containerd' }}
      shell: bash
      run: |
       colima nerdctl install
    - name: Print Colima logs
      if: always()
      shell: bash
      run: cat /Users/runner/.colima/_lima/colima/ha.stderr.log || true
    - name: Set Colima context
      shell: bash
      run: docker context use colima
