name: "Rancher Desktop Setup"
description: "Sets up Rancher Desktop"
inputs:
  runner:
    description: "The runner type (e.g., macos-latest)"
    default: macos-latest
runs:
  using: "composite"
  steps:
    - name: Rancher Desktop constraints
      shell: bash
      run: |
        if [[ ! "${{ inputs.runner }}" =~ ^macos.* ]]; then
          echo "::error::Rancher Desktop is only supported on macOS"
          exit 1
        fi
    - name: Rancher Desktop setup
      shell: bash
      run: |
        brew install --cask rancher

        TIMEOUT_SECS_CLI_TOOLS=240
        TIMEOUT_SECS_USER_SOCKET=300

        echo "Open Rancher Desktop app"
        open "/Applications/Rancher Desktop.app"

        GH_RD_BIN="/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/"

        echo "Wait max of ${TIMEOUT_SECS_CLI_TOOLS}s for Rancher Desktop to create CLI tools"
        for i in $(seq 1 ${TIMEOUT_SECS_CLI_TOOLS}); do
            if [ -e "${GH_RD_BIN}/rdctl" ]; then
              echo "Rancher Desktop CLI tools created after ${i}s"
              break
            fi
            echo "CLI tools not installed yet after ${i}. Waiting..."
            sleep 2
        done

        if [ ! -e "${GH_RD_BIN}/rdctl" ]; then
          echo "Rancher Desktop CLI tools not found"
          exit 1
        fi

        echo "Rancher Desktop initialised successfully, now configure the container runtime"
        "${GH_RD_BIN}/rdctl" set \
          --application.admin-access=false \
          --application.path-management-strategy=manual \
          --application.start-in-background=true \
          --container-engine.name=moby \
          --kubernetes.enabled=false \
          --virtual-machine.number-cpus=3 \
          --virtual-machine.memory-in-gb=14 \
          --verbose \
          || true

        echo "Restart Rancher Desktop"
        "${GH_RD_BIN}/rdctl" shutdown
        "${GH_RD_BIN}/rdctl" start

        echo "Wait max of ${TIMEOUT_SECS_USER_SOCKET}s for Rancher socket"

        for i in $(seq 1 ${TIMEOUT_SECS_USER_SOCKET}); do
            if [ -e "$HOME/.rd/docker.sock" ]; then
              echo "Rancher Desktop socket created after ${i}s"
              break
            fi
            sleep 1
        done

        if [ ! -e "$HOME/.rd/docker.sock" ]; then
          echo "Rancher Desktop socket not found"
          exit 1
        fi

        echo "{}" > $HOME/.docker/config.json

        docker context use rancher-desktop
