name: Run tests for a Go project

on:
  workflow_call:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  test-go-project:
    name: "test: ${{ matrix.platform }}/${{ matrix.container-runtime }}"
    strategy:
      fail-fast: false
      matrix:
        platform: ["ubuntu-latest"]
        container-runtime: ["containerd", "docker", "docker-rootless", "podman"]
        include:
          - platform: "macos-15-intel"
            container-runtime: "orbstack"
          - platform: "macos-15-intel"
            container-runtime: "docker"
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
            go-version-file: 'go.mod'
            cache-dependency-path: 'go.sum'
        id: go

      - name: ensure compilation
        run: go build ./...

      - name: Colima setup
        if: ${{ matrix.container-runtime == 'colima' }}
        uses: ./.github/actions/colima-setup
        with:
          runner: ${{ matrix.platform }}

      - name: Docker setup (containerd)
        if: ${{ matrix.container-runtime == 'containerd' }}
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 #v4.3.0
        with:
          rootless: false
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Docker setup (Rootfull)
        if: ${{ matrix.container-runtime == 'docker' && matrix.platform == 'ubuntu-latest' }}
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 #v4.3.0
        with:
          rootless: false
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": false
              }
            }

      - name: Docker setup (Rootless)
        if: ${{ matrix.container-runtime == 'docker-rootless' }}
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 #v4.3.0
        with:
          rootless: true
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": false
              }
            }

      - name: Orbstack setup
        if: ${{ matrix.container-runtime == 'orbstack' }}
        uses: ./.github/actions/orbstack-setup

      - name: Podman setup
        if: ${{ matrix.container-runtime == 'podman' }}
        uses: ./.github/actions/podman-setup

      - name: Rancher Desktop setup
        if: ${{ matrix.container-runtime == 'rancher' }}
        uses: ./.github/actions/rancher-desktop-setup
        with:
          runner: ${{ matrix.platform }}

      - name: Docker setup (macOS Intel with Lima)
        if: ${{ matrix.platform == 'macos-15-intel' && matrix.container-runtime == 'docker' }}
        uses: docker/setup-docker-action@b60f85385d03ac8acfca6d9996982511d8620a19 # v4.3.0
        env:
          LIMA_START_ARGS: --cpus 3 --memory 14

      - name: debug
        timeout-minutes: 30
        shell: bash
        run: |
          docker context ls
          # create the context directory to avoid errors in the CI worker because of no context is created
          mkdir -p "$HOME/.docker/contexts/meta"

      - name: go test
        timeout-minutes: 30
        shell: bash
        run: |
          go install gotest.tools/gotestsum@latest
          gotestsum \
            --format short-verbose \
            --packages="./..." \
            --junitfile TEST-unit.xml \
            -- \
            -v \
            -coverprofile=coverage.out \
            -timeout=5m \
            -race

      - name: Test Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
            paths: "**/TEST-unit*.xml"
        if: always()
