name: Run tests for a Go project
run-name: "${{ inputs.go-version }}"

on:
  workflow_call:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  test-go-project:
    name: "test: ${{ matrix.platform }}"
    strategy:
      matrix:
        platform: ["ubuntu-latest"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
            go-version: 'go.mod'
            cache-dependency-path: 'go.sum'
        id: go

      - name: ensure compilation
        run: go build ./...

      - name: debug
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        timeout-minutes: 30
        shell: bash
        run: docker context ls

      - name: go test
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        timeout-minutes: 30
        shell: bash
        run: make test

      - name: Test Summary
        uses: test-summary/action@31493c76ec9e7aa675f1585d3ed6f1da69269a86 # v2.4
        with:
            paths: "**/TEST-unit*.xml"
        if: always()
