name: Main pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: write  # for golangci-lint action to determine which PR to decorate
    uses: ./.github/workflows/ci-lint-go.yml

  test:
    needs:
      - lint
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for sonarsource/sonarcloud-github-action to determine which PR to decorate
    uses: ./.github/workflows/ci-test-go.yml
    secrets: inherit

  # This job serves as confirmation that all test jobs finished
  end:
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Check if any jobs failed
        if: ${{ failure() || cancelled() }}
        run: exit 1

      - run: echo "All tests completed successfully!"
